# KNN imputation : multivariate imputation, in order to fill a missing value.

fill the value , with the row which is similar to this one the most, (by euclidean distance)

2 step process.
1. find k nearest nabour.
2. find the value.
nan_euclidean_distance().

Finds euclidean distance of each row, col in order to find most likely column.

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [9]:
df = pd.read_csv(r'c:\Users\rajku\Downloads\archive (1)\Titanic-Dataset.csv')[['Age','Fare', 'Pclass', 'Survived']]

In [10]:
df.head()

    Age     Fare  Pclass  Survived
0  22.0   7.2500       3         0
1  38.0  71.2833       1         1
2  26.0   7.9250       3         1
3  35.0  53.1000       1         1
4  35.0   8.0500       3         0

In [11]:
df.isnull().mean()*100

Age         19.86532
Fare         0.00000
Pclass       0.00000
Survived     0.00000
dtype: float64

In [12]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [13]:
x_train , x_test, y_train , y_test = train_test_split(x,y, test_size=.2)

In [71]:
knn = KNNImputer(n_neighbors= 5, weights='distance')
x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.fit_transform(x_test)

In [72]:
pd.DataFrame(x_train_trf , columns=x_train.columns)

           Age     Fare  Pclass
0     7.000000  26.2500     2.0
1    35.000000   8.0500     3.0
2    25.000000   7.6500     3.0
3     3.000000  41.5792     2.0
4    16.000000  57.9792     1.0
..         ...      ...     ...
707  30.000000  93.5000     1.0
708  28.477287  69.5500     3.0
709  49.000000  89.1042     1.0
710   3.000000  18.7500     2.0
711  30.000000   7.2292     3.0

[712 rows x 3 columns]

In [73]:
lr = LogisticRegression()
lr.fit(x_train_trf, y_train)
y_pred = lr.predict(x_test_trf)

In [75]:
print(accuracy_score(y_test, y_pred))

0.7597765363128491