# Missing Indicator 
Making new column for showing missing values, (true/ false)

In [ ]:
# sometimes model learns how to diffrentiate
# btw missing and non missing values

In [16]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator, SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv(r'c:\Users\rajku\Downloads\train (1).csv', usecols=['Age', 'Fare', 'Survived'])

In [3]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [ ]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [91]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

In [10]:
x_train.head()

      Age     Fare
625  61.0  32.3208
345  24.0  13.0000
673  31.0  13.0000
105  28.0   7.8958
29    NaN   7.8958

In [92]:
s = SimpleImputer()
x_train_imputed = s.fit_transform(x_train)
x_test_imputed = s.transform(x_test)

In [ ]:
x_train_imputed

In [94]:
clf = LogisticRegression()
clf.fit(x_train_imputed, y_train)

LogisticRegression()

In [95]:
y_pred = clf.predict(x_test_imputed)
print(accuracy_score(y_test, y_pred))

0.664804469273743

In [87]:
mi = MissingIndicator()
mi.fit(x_train)
x_train_miss = mi.transform(x_train)
x_test_miss = mi.transform(x_test)

In [88]:
x_train['Age_NA'] = x_train_miss
x_test['Age_NA'] = x_test_miss

In [89]:
clf2 = LogisticRegression()
clf2.fit(x_train_miss, y_train)
# print(x_train)

LogisticRegression()

In [90]:
y_pred = clf2.predict(x_test_miss)
print(accuracy_score(y_pred, y_test))

0.6145251396648045

In [ ]:
si = SimpleImputer(add_indicator=True)          # inbuild perameter for missing value indicator
s = SimpleImputer()
x_train_imputed = si.fit_transform(x_train)
x_test_imputed = si.transform(x_test)

clf = LogisticRegression()
clf.fit(x_train_imputed, y_train)

y_pred = clf.predict(x_test_imputed)
print(accuracy_score(y_test, y_pred))

0.6368715083798883

# Automatically select value for imputaion